title: 山谷先生的投資獲利美學
description: |-
  不教你取巧的投資方式，只教你正確的投資觀念。
  只給你簡單易懂的投資知識，讓你不再盲目的地「靠感覺」投資。
head:
  - - meta
    - name: viewport
      content: width=device-width,user-scaleble=0,initial-scale=1.0,maximum-scale=1.0
  - - link
    - rel: stylesheet
      href: https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900
  - - link
    - rel: stylesheet
      href: https://cdn.jsdelivr.net/npm/@mdi/font@5.x/css/materialdesignicons.min.css
locales:
  /:
    lang: zh-TW
themeConfig:
  heroImage: ""
  disqus: ""
  nav:
    - text: Home
      link: /
      icon: mdi-home
    - text: What's VuePress
      link: /2020/05/10/vuepress-introduction/
      icon: mdi-vuejs
  color:
    $accentColor: "#00ad8d"
    $secondaryColor: "#1792cd"
  summary: true
  logo: /images/uploads/66856558_1054362901424289_1134833468883075072_n.png
  summaryLength: 100
  googleAnalytics: ""
  about:
    name: 山谷先生
    image: /images/uploads/66856558_1054362901424289_1134833468883075072_n.png
    position: ""
    bio: 曾任職花旗銀行、玉山銀行理財專員 XQ全球贏家官方合作講師 擁有10年實務投資經驗 擅長籌碼選股與技術分析
      以深入淺出的方式教學，讓投資人以輕鬆、快樂的方式學習理財與投資
  hostname: http://mr-valley.com/
  sitemap: true
  socialMedia:
    - type: facebook
      link: https://www.facebook.com/mrvalley.w/
